# Environment
environment:
  run_env: false
  name: "CartPoleSim"
  gravity: 15.0
  mass1: 0.1
  mass2: 1.0
  length: 18.0
  dt: 0.01
  max_action: 10.0
  damping: 0.0
  seed: 51
# Data Collection
collector:
  num_trajectories: 50
  episode_time: 1000
  policy_seed: 35
  save: true
  impulse_policy: true
# Datasets
datasets:
  use_existing: true
  paths:
    - "datasets/v0_CartPoleSim_*gravity15.000*_length18.000.npz"
# Model
model:
  run_model: true
  name: WorldModel
  state_dim: 5
  action_dim: 1
  hidden_dim: 64
  latent_dim: 3
# Trainer
trainer:
  run_trainer: true
  batch_size: 256
  steps: 100000
  log_interval: 100
# Rollout Engine
rollout_engine:
  run_rollouts: False
  horizon: 50
  zero_actions: False
# Hyperparameters
hyperparams:
  optimizer: Adam
  loss: MSE
  lr: 0.001
  rollout_steps: 5
  rollout_decay: "Linear"
  gamma: 0.9
# Checkpointing
checkpointing:
  save: true
  save_path: "model_saves/"
  load: False
  load_path: null
# Settings
settings:
  device: "cpu"