# Environment
environment:
 run_env: True
 name: "PendulumSim"
 gravity: 9.8
 pen_mass: 1.0
 pen_length: 1.0
 dt: 0.01
 max_torque: 2.0
 damping: 0.0
 seed: 42

# Data Collection Parameters
collector:
  run_collector: True
  num_trajectories: 50
  episode_time: 100
  policy_seed: 35
  save: True

# Model Parameterrs
model:
  run_model: True
  name: WorldModel
  state_dim: 3
  action_dim: 1
  hidden_dim: 64
  latent_dim: 8

# Training and Testing Parameters
trainer:
  run_trainer: False
  batch_size: 32
  steps: 100000
  log_interval: 100
# Visualizer Parameters

# Rollout Engine
rollout_engine:
  run_rollouts: False
  horizon: 1


# Hyperparameters
hyperparams:
  optimizer: Adam
  loss: MSE
  lr: 3e-4
  rollout_decay: "Linear"
  gamma: 0.9
  

checkpointing:
  save: True
  save_path: "checkpoints/"
  load: False
  load_path: null